In [2]:
import pandas as pd

In [9]:
brands=pd.read_csv("topic50/topic25brands.csv")
tags=pd.read_csv("topic50/topic25tags.csv")

brands=brands.rename(columns={'0':'brand','1':'counts'})
brands.counts=brands.counts/brands.counts.sum()

tags=tags.rename(columns={'0':'tag','1':'counts'})
tags.counts=tags.counts/tags.counts.sum()

In [10]:
brands[0:10]

         brand    counts
0           GU  0.249319
1       UNIQLO  0.111717
2         ZARA  0.062670
3     CONVERSE  0.061308
4     no brand  0.042916
5     Handmade  0.034741
6         ユニクロ  0.032016
7         しまむら  0.022480
8         WEGO  0.020436
9  GLOBAL WORK  0.019755

In [11]:
tags[0:20]

         tag    counts
0         GU  0.110276
1       プチプラ  0.042607
2      ぽっちゃり  0.035088
3   ママファッション  0.035088
4     ハンドメイド  0.035088
5    プチプラコーデ  0.032581
6     UNIQLO  0.030075
7      GUコーデ  0.020050
8      伊達メガネ  0.020050
9   ぽっちゃりコーデ  0.020050
10        妊婦  0.017544
11  オックスフォード  0.015038
12      しまむら  0.015038
13   ニットクラッチ  0.015038
14  マタニティコーデ  0.015038
15     ママコーデ  0.012531
16   ray ban  0.012531
17        厚底  0.012531
18     マタニティ  0.012531
19   スエットパンツ  0.010025

06 オトナ女子
08 大学生高校生
09 大学生
14 渋谷109
19 ストリート
24 ミリタリー
25 ぽっちゃりママ
28 ストリート
32 アウトドア